version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: "cimg/node:18.17.0"
    steps:
      - checkout
      - node/install:
          node-version: "18.17.0"
      - node/install-packages
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test